spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: @app.database.username@
    url: @app.database.url@
    password: @app.database.password@
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: 'false'
    show-sql: 'true'
    hibernate:
      ddl-auto: update